version: "3.8"

services:
  incube:
    image: fuadgrimaldi/fullstack-incube:latest
    container_name: incube
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env

  web:
    image: nginx:stable-alpine
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - incube
    networks:
      - incube-network
  db:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: incube
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./.docker/volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - incube-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - incube-network

networks:
  incube-network:
